/**
* These are images and other stylistic elements that 
* need to be published for the site to correctly style.
**/
import logo from '../assets/Logo.png'
import view from '../assets/View.jpg'
import tokyo from '../assets/Tokyo.jpg'
import banner from '../assets/banner.png'
import glass from '../assets/Glass.jpg'
import fi1 from '../assets/apple-touch-icon-114x114.png'
import fi2 from '../assets/apple-touch-icon-120x120.png'
import fi3 from '../assets/apple-touch-icon-144x144.png'
import fi4 from '../assets/apple-touch-icon-152x152.png'
import fi5 from '../assets/apple-touch-icon-57x57.png'
import fi6 from '../assets/apple-touch-icon-60x60.png'
import fi7 from '../assets/apple-touch-icon-72x72.png'
import fi8 from '../assets/apple-touch-icon-76x76.png'
import fi10 from '../assets/favicon-128.png'
import fi11 from '../assets/favicon-16x16.png'
import fi12 from '../assets/favicon-196x196.png'
import fi13 from '../assets/favicon-32x32.png'
import fi14 from '../assets/favicon-96x96.png'
import fi15 from '../assets/favicon.ico'
import fi16 from '../assets/mstile-144x144.png'
import fi17 from '../assets/mstile-150x150.png'
import fi18 from '../assets/mstile-310x150.png'
import fi19 from '../assets/mstile-310x310.png'
import fi20 from '../assets/mstile-70x70.png'
