# Configures a Kubernetes container service
# to run the website.

# Website
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas:  1
  template:
    metadata:
      labels:
        app:  website
    spec:
      containers:
      - name: website
        image: bashcorpacr.azurecr.io/website
        ports:
        - containerPort:  3000
          name: http-server
---
# Website load balancer
apiVersion: v1
kind:  Service
metadata:
  name:  website
spec:
  type:  LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app:  website
---
# Web server
apiVersion: apps/v1beta1
kind:  Deployment
metadata:
  name: reverseproxy
spec:
  replicas:  1
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image:  bashcorpacr.azurecr.io/reverseproxy
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
---
# Web server load balancer
apiVersion: v1
kind:  Service
metadata:
  name:  reverseproxy
spec:
  type:  LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app:  website
