apiVersion: v1
kind: Service
metadata:
  labels:
    name: webservice
  name: webservice
spec:
  serviceType: ClusterIP
  clusterIP: 10.0.0.1
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: website