apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: website
    type: node
  name: website
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: website
        type: node
    spec:
      containers:
      - image: bashcorp/website
        name: website
        ports:
        - name: website
          containerPort: 3000